import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Navbar } from '@/components/layout/Navbar';
import { operationsService } from '@/services/operationsService';
import { storageService } from '@/services/storageService';
import { AlertRule, OperationsAlert, ShiftGoals } from '@/types/operations';
import { useAuth } from '@/context/AuthContext';
import { OperationsKpiGrid } from '@/components/operations/OperationsKpiGrid';
import { OperationsQueueBoard } from '@/components/operations/OperationsQueueBoard';
import { OperationsAlertCenter } from '@/components/operations/OperationsAlertCenter';
import { ShiftGoalsPanel } from '@/components/operations/ShiftGoalsPanel';
import { DailyManagerSummary } from '@/components/operations/DailyManagerSummary';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { AlertTriangle, BellRing, CheckCircle2, RefreshCw, Save, Settings2 } from 'lucide-react';
import { toast } from 'sonner';

const healthStyle = { ON_TARGET: 'bg-emerald-500/15 border-emerald-500/40 text-emerald-300', ATTENTION: 'bg-amber-500/15 border-amber-500/40 text-amber-300', CRITICAL: 'bg-rose-500/15 border-rose-500/40 text-rose-300' };
const goalFields = [{ key: 'ticketTarget', label: 'Completed tickets' }, { key: 'inboundLbsTarget', label: 'Inbound pounds' }, { key: 'vehicleTarget', label: 'Vehicles processed' }, { key: 'averageTurnaroundMinutesTarget', label: 'Turnaround minutes' }, { key: 'grossMarginTarget', label: 'Gross margin ($)' }] as const;

export default function OperationsPage() {
  const { user, isAdmin } = useAuth(); const canManage = isAdmin || user?.role === 'yard_manager';
  const [goalsOpen, setGoalsOpen] = useState(false); const [rulesOpen, setRulesOpen] = useState(false);
  const [draft, setDraft] = useState<ShiftGoals>(storageService.getOperationsGoals()); const [rules, setRules] = useState<AlertRule[]>(storageService.getOperationsAlertRules());
  const { data: snapshot, refetch, isFetching } = useQuery({ queryKey: ['operations'], queryFn: () => operationsService.getSnapshot(), refetchInterval: 30000 });
  if (!snapshot) return <div className="min-h-screen bg-slate-950"><Navbar/></div>;
  const handleAlert = (alert: OperationsAlert, action: 'ACKNOWLEDGED' | 'RESOLVED' | 'SNOOZED') => { operationsService.updateAlert(alert, action, user?.fullName || 'Operator'); toast.success(action === 'SNOOZED' ? 'Alert snoozed for one hour' : `Alert ${action.toLowerCase()}`); void refetch(); };
  const saveGoals = () => { storageService.saveOperationsGoals({ ...draft, updatedAt: new Date().toISOString() }); setGoalsOpen(false); toast.success('Shift goals saved'); void refetch(); };
  const saveRules = () => { storageService.saveOperationsAlertRules(rules); setRulesOpen(false); toast.success('Alert rules saved'); void refetch(); };
  return <div className="min-h-screen bg-slate-950 text-slate-100"><Navbar/><main className="max-w-7xl mx-auto px-4 sm:px-6 py-5 space-y-5">
    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-5 sm:p-7 shadow-2xl"><div className="flex flex-col lg:flex-row gap-5 justify-between lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-[11px] uppercase tracking-[0.2em] text-emerald-400">Live operations</p><Badge className={`border ${healthStyle[snapshot.health]}`}>{snapshot.health.replace('_', ' ')}</Badge></div><h1 className="mt-2 text-3xl sm:text-4xl font-black tracking-tight">Operations Command Center</h1><p className="mt-2 text-sm text-slate-400">{new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })} · Current shift</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => void refetch()} variant="outline" className="border-slate-700 bg-slate-950"><RefreshCw className={`w-4 h-4 mr-2 ${isFetching ? 'animate-spin' : ''}`}/>Refresh</Button><Button onClick={() => snapshot.alerts.filter((alert) => alert.status === 'OPEN').forEach((alert) => handleAlert(alert, 'ACKNOWLEDGED'))} variant="outline" className="border-slate-700 bg-slate-950"><BellRing className="w-4 h-4 mr-2"/>Acknowledge alerts</Button>{canManage && <><Button onClick={() => { setRules(storageService.getOperationsAlertRules()); setRulesOpen(true); }} variant="outline" className="border-slate-700 bg-slate-950"><BellRing className="w-4 h-4 mr-2"/>Alert rules</Button><Button onClick={() => { setDraft(storageService.getOperationsGoals()); setGoalsOpen(true); }} className="bg-emerald-600 hover:bg-emerald-500"><Settings2 className="w-4 h-4 mr-2"/>Set shift goals</Button></>}</div></div></section>
    <OperationsKpiGrid metrics={snapshot.metrics}/><div className="grid xl:grid-cols-3 gap-4"><div className="xl:col-span-2"><OperationsQueueBoard queues={snapshot.queues}/></div><div className="space-y-4"><ShiftGoalsPanel goals={snapshot.goals} canManage={canManage} onConfigure={() => { setDraft(storageService.getOperationsGoals()); setGoalsOpen(true); }}/><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4 flex items-center gap-3"><div className={`p-2.5 rounded-xl ${snapshot.health === 'CRITICAL' ? 'bg-rose-500/15 text-rose-400' : snapshot.health === 'ATTENTION' ? 'bg-amber-500/15 text-amber-400' : 'bg-emerald-500/15 text-emerald-400'}`}>{snapshot.health === 'ON_TARGET' ? <CheckCircle2 className="w-5 h-5"/> : <AlertTriangle className="w-5 h-5"/>}</div><div><p className="font-bold text-sm">Operational health</p><p className="text-xs text-slate-400">{snapshot.health === 'ON_TARGET' ? 'Shift is tracking to plan.' : 'Review the active exception feed.'}</p></div></div></div></div><div className="grid xl:grid-cols-2 gap-4"><OperationsAlertCenter alerts={snapshot.alerts} canManage={canManage} onAction={handleAlert}/><DailyManagerSummary summary={snapshot.summary}/></div>
  </main><Dialog open={rulesOpen} onOpenChange={setRulesOpen}><DialogContent className="bg-slate-900 border-slate-700 text-slate-100 rounded-2xl"><DialogHeader><DialogTitle>Configure alert thresholds</DialogTitle></DialogHeader><div className="space-y-3">{rules.map((rule, index) => <div key={rule.id} className="grid grid-cols-[1fr_100px] gap-3 items-center"><Label className="text-xs text-slate-300">{rule.key.split('_').join(' ')}</Label><Input type="number" value={rule.threshold} onChange={(event) => setRules(rules.map((item, itemIndex) => itemIndex === index ? { ...item, threshold: Number(event.target.value) } : item))} className="bg-slate-950 border-slate-700"/></div>)}</div><Button onClick={saveRules} className="bg-emerald-600 hover:bg-emerald-500"><Save className="w-4 h-4 mr-2"/>Save alert rules</Button></DialogContent></Dialog><Dialog open={goalsOpen} onOpenChange={setGoalsOpen}><DialogContent className="bg-slate-900 border-slate-700 text-slate-100 rounded-2xl"><DialogHeader><DialogTitle>Configure current shift goals</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-4">{goalFields.map(({ key, label }) => <div key={key}><Label className="text-xs text-slate-400">{label}</Label><Input type="number" value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: Number(event.target.value) })} className="mt-1 bg-slate-950 border-slate-700"/></div>)}</div><Button onClick={saveGoals} className="bg-emerald-600 hover:bg-emerald-500"><Save className="w-4 h-4 mr-2"/>Save goals</Button></DialogContent></Dialog></div>;
}
