import React, { useMemo, useState } from 'react';
import { Navbar } from '@/components/layout/Navbar';
import { storageService } from '@/services/storageService';
import { scaleService } from '@/services/scaleService';
import { OutboundShipment, ShipmentStatus } from '@/types/scrap';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Truck, Plus, Scale, Factory, CheckCircle2, DollarSign } from 'lucide-react';
import { toast } from 'sonner';

const statuses: ShipmentStatus[] = ['STAGED', 'IN_TRANSIT', 'DELIVERED', 'SETTLED', 'DISCREPANCY'];
const statusStyle: Record<ShipmentStatus, string> = { STAGED:'bg-slate-700 text-slate-200', IN_TRANSIT:'bg-blue-500/20 text-blue-300', DELIVERED:'bg-amber-500/20 text-amber-300', SETTLED:'bg-emerald-500/20 text-emerald-300', DISCREPANCY:'bg-red-500/20 text-red-300' };
const money = (value: number) => value.toLocaleString(undefined, { style: 'currency', currency: 'USD' });

export default function ShipmentsPage() {
 const [shipments,setShipments]=useState(storageService.getShipments()); const [mills,setMills]=useState(storageService.getMills());
 const [filter,setFilter]=useState<'ALL'|ShipmentStatus>('ALL'); const [open,setOpen]=useState(false); const [selected,setSelected]=useState<OutboundShipment|null>(null);
 const refresh=()=>{setShipments(storageService.getShipments());setMills(storageService.getMills())};
 const filtered=filter==='ALL'?shipments:shipments.filter(s=>s.status===filter);
 const settled=shipments.filter(s=>s.status==='SETTLED'||s.status==='DISCREPANCY'); const mtd=settled.filter(s=>new Date(s.createdAt).getMonth()===new Date().getMonth()).reduce((a,s)=>a+(s.settlement?.amountPaid??0),0);
 return <div className="min-h-screen bg-slate-950 text-slate-100"><Navbar/><main className="max-w-7xl mx-auto p-4 sm:p-6 space-y-6">
  <section className="flex flex-col sm:flex-row gap-4 justify-between sm:items-end"><div><p className="text-emerald-400 font-mono text-xs tracking-[.2em]">SELL-SIDE OPERATIONS</p><h1 className="text-3xl font-black">Mill Shipments</h1><p className="text-slate-400">From yard scale to settlement reconciliation.</p></div><Button onClick={()=>setOpen(true)} className="bg-emerald-600 hover:bg-emerald-500 rounded-xl"><Plus className="w-4 h-4 mr-2"/>New load</Button></section>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{([['Open loads',String(shipments.filter(s=>['STAGED','IN_TRANSIT'].includes(s.status)).length),Truck],['Settled MTD',money(mtd),DollarSign],['Pending settlement',String(shipments.filter(s=>s.status==='DELIVERED').length),Factory],['Avg variance',settled.length?`${(settled.reduce((a,s)=>a+Math.abs(((s.settlement?.amountPaid??s.expectedRevenue)-s.expectedRevenue)/Math.max(s.expectedRevenue,1))*100,0)/settled.length).toFixed(1)}%`:'—',Scale]] as [string,string,typeof Truck][]).map(([l,v,Icon])=><Card key={l} className="bg-slate-900 border-slate-800 rounded-2xl"><CardContent className="p-4"><Icon className="w-4 h-4 text-emerald-400 mb-3"/><p className="text-xs text-slate-400">{l}</p><p className="font-mono font-black text-xl">{v}</p></CardContent></Card>)}</div>
  <Card className="bg-slate-900 border-slate-800 rounded-2xl"><CardHeader className="flex-row justify-between items-center"><CardTitle>Load ledger</CardTitle><Select value={filter} onValueChange={v=>setFilter(v as typeof filter)}><SelectTrigger className="w-40 bg-slate-950 border-slate-700"><SelectValue/></SelectTrigger><SelectContent>{['ALL',...statuses].map(s=><SelectItem key={s} value={s}>{s.replace('_',' ')}</SelectItem>)}</SelectContent></Select></CardHeader><CardContent className="space-y-3">{filtered.length===0?<div className="py-16 text-center text-slate-500"><Truck className="w-10 h-10 mx-auto mb-3"/>No loads yet. Create a shipment when processed metal leaves the yard.</div>:filtered.map(s=><button key={s.id} onClick={()=>setSelected(s)} className="w-full text-left rounded-xl border border-slate-800 bg-slate-950/50 p-4 hover:border-emerald-500/40 transition-colors"><div className="flex justify-between gap-3"><div><p className="font-bold">{s.loadNumber} <span className="text-slate-400 font-normal">• {s.millName}</span></p><p className="text-sm text-slate-400">{s.materialCategory} · {s.netWeightLbs.toLocaleString()} lbs · expected {money(s.expectedRevenue)}</p></div><Badge className={statusStyle[s.status]}>{s.status.replace('_',' ')}</Badge></div></button>)}</CardContent></Card>
  <Card className="bg-slate-900 border-slate-800 rounded-2xl"><CardHeader><CardTitle>Mill directory</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-3">{mills.map(m=><div key={m.id} className="rounded-xl bg-slate-950 border border-slate-800 px-4 py-3"><b>{m.name}</b><p className="text-xs text-slate-400">{m.contactName||'No contact'} {m.phone?`· ${m.phone}`:''}</p></div>)}<Button variant="outline" onClick={()=>{const name=window.prompt('Mill or processor name');if(name){storageService.saveMill({id:`mill-${Date.now()}`,name,createdAt:new Date().toISOString()});refresh();}}} className="border-slate-700">+ Add mill</Button></CardContent></Card>
 </main><ShipmentForm open={open} onOpenChange={setOpen} mills={mills} onSaved={refresh}/><Settlement shipment={selected} onClose={()=>setSelected(null)} onSaved={refresh}/></div>
}
function ShipmentForm({open,onOpenChange,mills,onSaved}:{open:boolean;onOpenChange:(v:boolean)=>void;mills:{id:string;name:string}[];onSaved:()=>void}){const [f,setF]=useState({millName:'',materialCategory:'Ferrous',trailerNumber:'',driverName:'',grossWeightLbs:0,tareWeightLbs:0,rate:0});const net=Math.max(0,f.grossWeightLbs-f.tareWeightLbs);const capture=(field:'grossWeightLbs'|'tareWeightLbs')=>setF({...f,[field]:scaleService.getStatus().weight});const save=()=>{if(!f.millName.trim()||net<=0){toast.error('Add a mill and valid gross/tare weights');return}const s:OutboundShipment={id:`ship-${Date.now()}`,loadNumber:`LD-${new Date().getFullYear()}-${String(Date.now()).slice(-5)}`,millName:f.millName,materialCategory:f.materialCategory,trailerNumber:f.trailerNumber,driverName:f.driverName,grossWeightLbs:f.grossWeightLbs,tareWeightLbs:f.tareWeightLbs,netWeightLbs:net,expectedRatePerLb:f.rate,expectedRevenue:net*f.rate,status:'STAGED',createdAt:new Date().toISOString()};storageService.saveShipment(s);toast.success('Load staged');onSaved();onOpenChange(false)};return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="bg-slate-900 border-slate-700 text-white max-w-lg"><DialogHeader><DialogTitle>Stage outbound load</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-3">{[['Mill / processor','millName'],['Material','materialCategory'],['Trailer / bin','trailerNumber'],['Driver','driverName']].map(([l,k])=><div key={k} className={k==='millName'||k==='materialCategory'?'col-span-2':''}><Label>{l}</Label><Input list={k==='millName'?'mills':undefined} value={f[k as keyof typeof f] as string} onChange={e=>setF({...f,[k]:e.target.value})} className="bg-slate-950 border-slate-700 mt-1"/></div>)}<datalist id="mills">{mills.map(m=><option key={m.id} value={m.name}/>)}</datalist>{(['grossWeightLbs','tareWeightLbs'] as const).map(k=><div key={k}><Label>{k==='grossWeightLbs'?'Gross lbs':'Tare lbs'}</Label><div className="flex gap-2 mt-1"><Input type="number" value={f[k]} onChange={e=>setF({...f,[k]:Number(e.target.value)})} className="bg-slate-950 border-slate-700"/><Button type="button" size="icon" variant="outline" onClick={()=>capture(k)}><Scale className="w-4 h-4"/></Button></div></div>)}<div><Label>Rate / lb</Label><Input type="number" step=".001" value={f.rate} onChange={e=>setF({...f,rate:Number(e.target.value)})} className="bg-slate-950 border-slate-700 mt-1"/></div></div><div className="rounded-xl bg-emerald-500/10 p-3 text-sm">Net <b>{net.toLocaleString()} lbs</b> · Expected <b>{money(net*f.rate)}</b></div><Button onClick={save} className="bg-emerald-600">Stage shipment</Button></DialogContent></Dialog>}
function Settlement({shipment,onClose,onSaved}:{shipment:OutboundShipment|null;onClose:()=>void;onSaved:()=>void}){const [actual,setActual]=useState('');const [paid,setPaid]=useState('');if(!shipment)return null;const save=()=>{const actualWeight=Number(actual)||shipment.netWeightLbs;const amount=Number(paid);if(!amount){toast.error('Enter the amount paid');return}const variance=Math.abs(amount-shipment.expectedRevenue)/Math.max(shipment.expectedRevenue,1)*100;storageService.saveShipment({...shipment,status:variance>2?'DISCREPANCY':'SETTLED',deliveredAt:shipment.deliveredAt||new Date().toISOString(),settlement:{scaleTicketNumber:`MILL-${Date.now().toString().slice(-6)}`,actualNetWeightLbs:actualWeight,actualRatePerLb:amount/actualWeight,deductions:0,amountPaid:amount,settledAt:new Date().toISOString()}});toast.success(variance>2?'Settlement saved with discrepancy flag':'Settlement reconciled');onSaved();onClose()};return <Dialog open={!!shipment} onOpenChange={v=>!v&&onClose()}><DialogContent className="bg-slate-900 border-slate-700 text-white"><DialogHeader><DialogTitle>{shipment.loadNumber} · settlement</DialogTitle></DialogHeader><p className="text-sm text-slate-400">Expected {money(shipment.expectedRevenue)} from {shipment.netWeightLbs.toLocaleString()} lbs.</p><Label>Mill net weight (lbs)</Label><Input type="number" placeholder={String(shipment.netWeightLbs)} value={actual} onChange={e=>setActual(e.target.value)} className="bg-slate-950 border-slate-700"/><Label>Actual amount paid</Label><Input type="number" placeholder="0.00" value={paid} onChange={e=>setPaid(e.target.value)} className="bg-slate-950 border-slate-700"/><Button onClick={save} className="bg-emerald-600"><CheckCircle2 className="w-4 h-4 mr-2"/>Reconcile settlement</Button></DialogContent></Dialog>}
