DROP ROLE IF EXISTS ${DB_USER};
SQL

DB_PASSWORD="jhilliard"
runuser -u postgres -- psql --set ON_ERROR_STOP=1 <<SQL
CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};
SQL

rm -rf "${INSTALL_DIR}"