import { Link } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { OperationsQueueEntry, OperationsQueueType } from '@/types/operations';
import { ArrowUpRight, Car, ClipboardCheck, Container, ReceiptText, Truck } from 'lucide-react';
const titles: Record<OperationsQueueType, string> = { INTAKE: 'Intake queue', VEHICLE: 'Vehicle workflow', SHIPMENT: 'Shipments', CONTAINER: 'Containers', COMPLIANCE: 'Compliance' };
const icons = { INTAKE: ReceiptText, VEHICLE: Car, SHIPMENT: Truck, CONTAINER: Container, COMPLIANCE: ClipboardCheck };
const age = (minutes: number) => minutes >= 1440 ? `${Math.floor(minutes / 1440)}d` : `${minutes}m`;
export function OperationsQueueBoard({ queues }: { queues: Record<OperationsQueueType, OperationsQueueEntry[]> }) { return <div className="grid lg:grid-cols-2 gap-3 sm:gap-4">{(Object.keys(queues) as OperationsQueueType[]).map((type) => { const Icon = icons[type]; const entries = queues[type]; return <Card key={type} className="rounded-2xl border-slate-800 bg-slate-900 overflow-hidden"><CardHeader className="p-3.5 sm:p-4 border-b border-slate-800 bg-slate-950/60 flex-row items-center justify-between"><CardTitle className="text-sm flex items-center gap-2"><Icon className="w-4 h-4 text-emerald-400"/>{titles[type]} <Badge className="bg-slate-800 text-slate-300 border-0">{entries.length}</Badge></CardTitle></CardHeader><CardContent className="p-2">{entries.length ? entries.slice(0, 5).map((entry) => <Link key={entry.id} to={entry.link} className="flex min-h-16 items-center gap-2.5 p-3 rounded-xl active:bg-slate-800 hover:bg-slate-800 transition-colors"><span className={`w-2 h-2 rounded-full shrink-0 ${entry.priority === 'URGENT' ? 'bg-rose-400' : entry.priority === 'ATTENTION' ? 'bg-amber-400' : 'bg-emerald-400'}`}/><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-100 truncate">{entry.title}</p><p className="text-[11px] sm:text-xs text-slate-400 truncate">{entry.detail}{entry.owner ? ` · ${entry.owner}` : ''}</p></div><div className="w-8 shrink-0 text-right"><p className="font-mono text-xs text-slate-300">{age(entry.elapsedMinutes)}</p><ArrowUpRight className="ml-auto mt-1 w-4 h-4 text-slate-500"/></div></Link>) : <p className="p-5 text-sm text-slate-500">No active work in this queue.</p>}</CardContent></Card> })}</div>; }
